"""Add Agent model and update Booking model

Revision ID: 32c5e3a3949a
Revises: c59681201e77
Create Date: 2025-05-09 09:59:23.776232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c5e3a3949a'
down_revision = 'c59681201e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultant', sa.String(length=100), nullable=False))
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('agent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('consultant')

    # ### end Alembic commands ###
