"""Add Agent model and update Booking model

Revision ID: 411b618cf91f
Revises: 463cd982f085
Create Date: 2025-05-09 10:15:29.043720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411b618cf91f'
down_revision = '463cd982f085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('agent')

    # ### end Alembic commands ###
