"""Add Agent model and update Booking model

Revision ID: 463cd982f085
Revises: 40a8ce9971c5
Create Date: 2025-05-09 10:14:27.144263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463cd982f085'
down_revision = '40a8ce9971c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('agent')

    # ### end Alembic commands ###
