"""Add Agent model and update Booking model

Revision ID: 6398c97cbebc
Revises: b89e826094da
Create Date: 2025-05-09 10:01:41.942849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6398c97cbebc'
down_revision = 'b89e826094da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultant', sa.String(length=100), nullable=True))
        batch_op.drop_column('agent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('consultant')

    # ### end Alembic commands ###
